DROP TABLE shop_ingredient;
DROP TABLE restaurant_recipe;
DROP TABLE user_recipe;
DROP TABLE recipe_ingredient;
DROP TABLE shop;
DROP TABLE restaurant;
DROP TABLE user;
DROP TABLE recipe;
DROP TABLE ingredient;